### ISSUE TITLE
How to get gfortran or ifort to find the ferror.mod file?

### ISSUE THREAD

**Issue by matt8s** [jchristopherson/linalg#7]
I am using the CMake files to compile your repositories. I cloned ferror, created a folder called "build" in ferror, and ran Cmake inside the build folder successfully. I was then able to build ferror and install it.

Next, I attempted to do the same for linalg. Linalg, of course, depends on ferror. However, the compilation does not work for linalg. Cmake does find the ferror package, because I gave the path as a command line option to Cmake. But the gfortran and ifort compilers are unable to find the ferror.mod file or shared libraries. Could the Cmake file for linalg correctly provide the ferror include paths to the Fortran compiler, so that the compiler can link ferror into the linalg executables? How would this be implemented in Cmake?

Some of the debug output follows. When I run CMake, I do get the message:
-- FERROR library found.
When I enter
cmake --build .
with gfortran, I get the error:
/linalg/src/linalg_core.f90:17:8:

     use ferror, only : errors
        1
Fatal Error: Can't open module file ‘ferror.mod’ for reading at (1): No such file or directory
compilation terminated.

With ifort, I get the error:

Building Fortran object src/CMakeFiles/linalg.dir/linalg_core.f90.o
/home/u31/spotnitz/linalg/src/linalg_core.f90(17): error #7002: Error in opening the compiled module file.  Check INCLUDE paths.   [FERROR]
    use ferror, only : errors
--------^

**Comment by Beliavsky** [comment]
I had the same problem. I compiled the ferror.f90 file separately and copied the ferror.mod and ferror.o file the /linalg/src directory, and then the build process worked.

**Comment by jchristopherson** [comment]
The build process has been reworked significantly, and this should no longer be an issue.  I'm closing the issue at this point.
