### ISSUE TITLE
linalg_test failing initially but passing with rerun; ferror.h is not placed correctly

### ISSUE THREAD

**Issue by barracuda156** [jchristopherson/linalg#9]
Weird results with test: if `ctest test` is run, `linalg_test` fails. However when I rerun with `ctest test --rerun-failed --output-on-failure`, it passes. Tried twice, it is reproducible.

```
10:linalg-1.7.1 svacchanda$ /usr/bin/sudo ctest test
Test project /opt/local/var/macports/build/_opt_PPCRosettaPorts_math_linalg/linalg/work/jchristopherson-linalg-76e7aad
    Start 1: linalg_test
1/2 Test #1: linalg_test ......................***Failed    3.64 sec
    Start 2: linalg_c_test
2/2 Test #2: linalg_c_test ....................   Passed    0.66 sec

50% tests passed, 1 tests failed out of 2

Total Test time (real) =   4.33 sec

The following tests FAILED:
	  1 - linalg_test (Failed)
Errors while running CTest
Output from these tests are in: /opt/local/var/macports/build/_opt_PPCRosettaPorts_math_linalg/linalg/work/linalg-1.7.1/Testing/Temporary/LastTest.log
Use "--rerun-failed --output-on-failure" to re-run the failed cases verbosely.
10:linalg-1.7.1 svacchanda$ /usr/bin/sudo ctest test --rerun-failed --output-on-failure
Test project /opt/local/var/macports/build/_opt_PPCRosettaPorts_math_linalg/linalg/work/jchristopherson-linalg-76e7aad
    Start 1: linalg_test
1/1 Test #1: linalg_test ......................   Passed    3.84 sec

100% tests passed, 0 tests failed out of 1

Total Test time (real) =   3.86 sec
```

P. S. Also the build cannot find `ferror.h` in `ferror-src/include`, since relevant flag is not passed. I had to copy that header to `ferror-build/include`.

**Comment by jchristopherson** [comment]
Hi @barracuda156, interesting.  I'll try and replicate the failure on my end.  My first suspicion is related to how I use a lot of random number generation for creating test matrix cases and have had issues with those causing failures in the past.  The issues I've run into relate to the random generation producing matrices sufficiently close to singular to cause problems in routines that don't play well with such matrices.  I'll let you know what I find.

As for the ferror header issue, I'm actually working on an update to that library now and will fix as part of that update.  Stay tuned, but this shouldn't be too long before I get it fixed.

**Comment by barracuda156** [comment]
@jchristopherson Thank you for responding!

(I intended to bring `linalg` into Macports, but looks like I rather wait until your update first.)

**Comment by jchristopherson** [comment]
Hi @barracuda156.  I've made updates that should fix the issues you've highlighted.  I have some other open action items, but feel free to test things out and let me know if you still have any issues.

**Comment by barracuda156** [comment]
> Hi @barracuda156. I've made updates that should fix the issues you've highlighted. I have some other open action items, but feel free to test things out and let me know if you still have any issues.

Thank you. By the way, is there any problem with `BUILD_C_API` at the moment or you just added an option to build it or not?

**Comment by jchristopherson** [comment]
There are a few issues with the complex-valued routines.  However, I added the BUILD_C_API flag as an option to allow the user to choose whether they wanted it or not regardless of the status of any of the routines.

**Comment by barracuda156** [comment]
@jchristopherson So the build error due to `ferror.h` is fixed (expectedly). Tests still fail and pass randomly:
```
10:linalg-61747861b4491d21d637debb9c7fb86fced738c4 svacchanda$ /usr/bin/sudo ctest test --rerun-failed --output-on-failure
Test project /opt/local/var/macports/build/_opt_PPCRosettaPorts_math_linalg/linalg/work/jchristopherson-linalg-6174786
    Start 1: linalg_test
1/1 Test #1: linalg_test ......................***Failed    3.25 sec
Test Failed: Asymmetric Eigen Values Test 2
STOP 1


0% tests passed, 1 tests failed out of 1

Total Test time (real) =   3.28 sec

The following tests FAILED:
	  1 - linalg_test (Failed)
Errors while running CTest
10:linalg-61747861b4491d21d637debb9c7fb86fced738c4 svacchanda$ /usr/bin/sudo ctest test --rerun-failed --output-on-failure
Test project /opt/local/var/macports/build/_opt_PPCRosettaPorts_math_linalg/linalg/work/jchristopherson-linalg-6174786
    Start 1: linalg_test
1/1 Test #1: linalg_test ......................   Passed    3.26 sec

100% tests passed, 0 tests failed out of 1

Total Test time (real) =   3.29 sec
```
These two are successive runs from the same build.

**Comment by barracuda156** [comment]
Also install fails:
```
CMake Error at _deps/ferror-build/install/cmake_install.cmake:81 (file):
  file INSTALL cannot find
  "/opt/local/var/macports/build/_opt_PPCRosettaPorts_math_linalg/linalg/work/linalg-61747861b4491d21d637debb9c7fb86fced738c4/_deps/ferror-src/doc/html":
  No such file or directory.
Call Stack (most recent call first):
  _deps/ferror-build/cmake_install.cmake:52 (include)
  dependencies/ferror/cmake_install.cmake:42 (include)
  dependencies/cmake_install.cmake:52 (include)
  cmake_install.cmake:47 (include)


make: *** [install/fast] Error 1
```

**Comment by jchristopherson** [comment]
OK.  Thanks for letting me know.  I'll dig into this as well.

**Comment by jchristopherson** [comment]
That was an easy fix.  It was related to the underlying ferror library having a change.  The error resulted from the install script of that library.  I'd recommend starting with a clean build and you should be fine.

**Comment by barracuda156** [comment]
@jchristopherson Tests issue might be `OpenBLAS`-related. I have set the build to use `vecLibFort` instead, and all looks good now from the first run:
```
--->  Testing linalg
Executing:  cd "/opt/local/var/macports/build/_opt_PPCRosettaPorts_math_linalg/linalg/work/build" && ctest test 
Test project /opt/local/var/macports/build/_opt_PPCRosettaPorts_math_linalg/linalg/work/build
    Start 1: linalg_test
1/3 Test #1: linalg_test ......................   Passed    0.75 sec
    Start 2: linalg_c_test
2/3 Test #2: linalg_c_test ....................   Passed    0.28 sec
    Start 3: fth_test
3/3 Test #3: fth_test .........................   Passed    0.02 sec

100% tests passed, 0 tests failed out of 3

Total Test time (real) =   1.13 sec
```

**Comment by jchristopherson** [comment]
Good to know. I set up a Linux and MacOS CI process using both gfortran and ifort. I’ll keep an eye on this to help monitor for issues. 

Thanks for your help and input so far!

**Comment by jchristopherson** [comment]
Hi @barracuda156.  I've finished my updates to the library, including adding additional test cases and CI processes.  If everything is working properly for you, I'm inclined to close out this issue.  I'll wait for your response, however.

**Comment by barracuda156** [comment]
> Hi @barracuda156.  I've finished my updates to the library, including adding additional test cases and CI processes.  If everything is working properly for you, I'm inclined to close out this issue.  I'll wait for your response, however.

@jchristopherson Let me try today. Thank you.

**Comment by barracuda156** [comment]
Thanks, all is good, closing.
